# Generated by Django 4.2.5 on 2023-10-02 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("watchlist_app", "0005_watchlist_avg_rating_watchlist_number_rating"),
    ]

    operations = [
        migrations.RenameField(
            model_name="review",
            old_name="created_at",
            new_name="created",
        ),
        migrations.RenameField(
            model_name="review",
            old_name="updated_at",
            new_name="update",
        ),
        migrations.RenameField(
            model_name="watchlist",
            old_name="created_at",
            new_name="created",
        ),
        migrations.AlterField(
            model_name="streamplatform",
            name="about",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="streamplatform",
            name="website",
            field=models.URLField(max_length=100),
        ),
    ]
